Models/ErrorViewModel.cs
namespace FishBuddy.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/FishContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace FishBuddy.Models
{
    public class FishContext : DbContext
    {
        public FishContext(DbContextOptions<FishContext> options) : base(options)
        { }
        public DbSet<FishSpecies> FishList { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<FishSpecies>().HasData(
                new FishSpecies
                {
                    ID = 1,
                    FishName = "Largemouth Bass",
                    Location = "Lakes, Rivers, & Ponds",
                    MaxLength = "27 Inches",
                    MaxWeight = "11.94 Pounds"

                },
                new FishSpecies
                {
                    ID = 2,
                    FishName = "Northern Pike",
                    Location = "Lakes, Rivers, & Ponds",
                    MaxLength = "51.5 Inches",
                    MaxWeight = "39 Pounds"
                },
                new FishSpecies
                {
                    ID = 3,
                    FishName = "Walleye",
                    Location = "Lakes, Rivers, & Ponds",
                    MaxLength = "35 Inches",
                    MaxWeight = "17.19 Pounds"
                }
            );

        }
    }
}

Models/FishSpecies.cs
using System.ComponentModel.DataAnnotations;
using System.Reflection;

namespace FishBuddy.Models
{ 
       public enum ExpLevel
{
    Begginer,
    Intermediate,
    Expert 
}

    public enum Season
    {
        Spring,
        Summer,
        Fall,
        Winter 
    }
    public class FishSpecies
    {
        public int ID { get; set; }

        [Required]
        [Display(Name = "Fish Name")]
        [StringLength(30, ErrorMessage = "Please enter a fish name 30 characters or less.")]
        public string? FishName { get; set; }


        [Display(Name = "Location")]
        public string? Location { get; set; }

        [Display(Name = "Experience Level")]
        public ExpLevel? ExperienceLevel { get; set; }

        [Display(Name = "Maximum Length")]
        public string? MaxLength { get; set; }

        [Display(Name = "Maximum Weight")]
        public string? MaxWeight { get; set; }

        [Display(Name = "Best Season T0 Catch")]
        public Season? BestSeason { get; set; }


    }
}

Controllers/FishSpeciesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FishBuddy.Models;

namespace FishBuddy.Controllers
{
    public class FishSpeciesController : Controller
    {
        private readonly FishContext _context;

        public FishSpeciesController(FishContext context)
        {
            _context = context;
        }

        // GET: FishSpecies
        public async Task<IActionResult> Index()
        {
              return _context.FishList != null ? 
                          View(await _context.FishList.ToListAsync()) :
                          Problem("Entity set 'FishContext.FishList'  is null.");
        }

        // GET: FishSpecies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.FishList == null)
            {
                return NotFound();
            }

            var fishSpecies = await _context.FishList
                .FirstOrDefaultAsync(m => m.ID == id);
            if (fishSpecies == null)
            {
                return NotFound();
            }

            return View(fishSpecies);
        }

        // GET: FishSpecies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: FishSpecies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,FishName,Location,ExperienceLevel,MaxLength,MaxWeight,BestSeason")] FishSpecies fishSpecies)
        {
            if (ModelState.IsValid)
            {
                _context.Add(fishSpecies);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(fishSpecies);
        }

        // GET: FishSpecies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.FishList == null)
            {
                return NotFound();
            }

            var fishSpecies = await _context.FishList.FindAsync(id);
            if (fishSpecies == null)
            {
                return NotFound();
            }
            return View(fishSpecies);
        }

        // POST: FishSpecies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,FishName,Location,ExperienceLevel,MaxLength,MaxWeight,BestSeason")] FishSpecies fishSpecies)
        {
            if (id != fishSpecies.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fishSpecies);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FishSpeciesExists(fishSpecies.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fishSpecies);
        }

        // GET: FishSpecies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.FishList == null)
            {
                return NotFound();
            }

            var fishSpecies = await _context.FishList
                .FirstOrDefaultAsync(m => m.ID == id);
            if (fishSpecies == null)
            {
                return NotFound();
            }

            return View(fishSpecies);
        }

        // POST: FishSpecies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.FishList == null)
            {
                return Problem("Entity set 'FishContext.FishList'  is null.");
            }
            var fishSpecies = await _context.FishList.FindAsync(id);
            if (fishSpecies != null)
            {
                _context.FishList.Remove(fishSpecies);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FishSpeciesExists(int id)
        {
          return (_context.FishList?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

Controllers/HomeController.cs
using FishBuddy.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace FishBuddy.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public ActionResult About()
        {
            return View();
        }
        public ActionResult Contact()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/FishSpecies/Create.cshtml
@model FishBuddy.Models.FishSpecies

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>FishSpecies</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FishName" class="control-label"></label>
                <input asp-for="FishName" class="form-control" />
                <span asp-validation-for="FishName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExperienceLevel" class="control-label"></label>
                <input asp-for="ExperienceLevel" class="form-control" />
                <span asp-validation-for="ExperienceLevel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxLength" class="control-label"></label>
                <input asp-for="MaxLength" class="form-control" />
                <span asp-validation-for="MaxLength" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxWeight" class="control-label"></label>
                <input asp-for="MaxWeight" class="form-control" />
                <span asp-validation-for="MaxWeight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BestSeason" class="control-label"></label>
                <input asp-for="BestSeason" class="form-control" />
                <span asp-validation-for="BestSeason" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/FishSpecies/Delete.cshtml
@model FishBuddy.Models.FishSpecies

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>FishSpecies</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FishName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FishName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExperienceLevel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExperienceLevel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaxLength)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaxLength)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaxWeight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaxWeight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BestSeason)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BestSeason)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/FishSpecies/Details.cshtml
@model FishBuddy.Models.FishSpecies

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>FishSpecies</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FishName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FishName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExperienceLevel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExperienceLevel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaxLength)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaxLength)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaxWeight)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaxWeight)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BestSeason)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BestSeason)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/FishSpecies/Edit.cshtml
@model FishBuddy.Models.FishSpecies

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>FishSpecies</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="FishName" class="control-label"></label>
                <input asp-for="FishName" class="form-control" />
                <span asp-validation-for="FishName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExperienceLevel" class="control-label"></label>
                <input asp-for="ExperienceLevel" class="form-control" />
                <span asp-validation-for="ExperienceLevel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxLength" class="control-label"></label>
                <input asp-for="MaxLength" class="form-control" />
                <span asp-validation-for="MaxLength" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaxWeight" class="control-label"></label>
                <input asp-for="MaxWeight" class="form-control" />
                <span asp-validation-for="MaxWeight" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BestSeason" class="control-label"></label>
                <input asp-for="BestSeason" class="form-control" />
                <span asp-validation-for="BestSeason" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/FishSpecies/Index.cshtml
@model IEnumerable<FishBuddy.Models.FishSpecies>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FishName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExperienceLevel)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaxLength)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaxWeight)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BestSeason)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FishName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Location)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ExperienceLevel)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxLength)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxWeight)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BestSeason)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/About.cshtml
@{
    ViewData["Title"] = "FishBuddy";
}
<div class="p-5 ms-0 mb-4 shadow" style="background-color:cornflowerblue;border-radius:30px;">
    <h2>
        FishBuddy
        
    </h2>
</div>
<div class="ms-4">
    <p>
        FishBuddy is an app for Michigan fishers of all experience levels looking to take out some of the guesswork from fishing.
        Discover some of the local species, recommended lures for them, and optimal timing & weather conditions when to catch them.
        
        We are always looking to improve our application.  Please contact our <a href="mailto:design@FishBuddy.com">Creative Team</a> with your ideas!
    </p>
</div>

Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "FishBuddy";
}
<div class="p-5 ms-0 mb-4 shadow" style="background-color:cornflowerblue;border-radius:30px;">
    <h2>FishBuddy</i></h2>
    <h3>A fishing app made by fishers for fishers</h3>
</div>
<div class="ms-3">
    <address>
        20935 Red Oak Drive<br />
        Lake Ann, MI 49650<br />
        <i class="fa fa-phone" style="font-size:24px"></i> 800.777.FISH
    </address>

    <address>
        <strong>Tech Support:</strong>   <a href="mailto:Support@fishbuddy.com">Support@fishbuddy.com</a><br />
        <strong>Sales/Marketing:</strong> <a href="mailto:Marketing@fishbuddy.com">Marketing@fishbuddy.com</a>
    </address>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Fishbuddy";
}

<div class="p-5 mb-4 shadow" style="background-color:cornflowerblue;border-radius:30px;">
    <h1>FishBuddy <i class="fa-solid fa-fish" style="font-size:20px;"></i></h1>
    <p class="lead">
       The FishBuddy app aims to display relevant information for multiple species of fish in the Michigan area, such as recommended lures, best times of day to fish, optimal weather conditions, and more!
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Fish Species</h2>
        <p> A comprehensive list of popular game fish species in Michigan.
            
        </p>
        <img src="~/images/bass.jpg" alt="someone holding a bass" asp-append-version="true"
             class="float-sm-start img-fluid col-sm-4  shadow rounded-sm" />
    </div>
    <div class="col-md-4">
        <h2>Lures</h2>
        <p>Check out which lures are best for certain species.</p>
        <img src="~/images/lure.jpg" alt="a spinner lure" asp-append-version="true"
             class="float-sm-start img-fluid col-sm-4  shadow rounded-sm" />
    </div>
    <div class="col-md-4">
        <h2>Best Times To Fish</h2>
        <p>Find the best times to fish for certain species.</p>
        <img src="~/images/sun.jpg" alt="a sunset" asp-append-version="true"
             class="float-sm-start img-fluid col-sm-4  shadow rounded-sm" />
    </div>

    <div class="col-md-4">
        <h2>Weather Conditions</h2>
        <p>See what weather conditions help you land specific fish.</p>
        <img src="~/images/clouds.jpg" alt="cloudy sky" asp-append-version="true"
             class="float-sm-start img-fluid col-sm-4  shadow rounded-sm" />
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FishBuddy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/FishBuddy.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/fit.css" />
 
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FishBuddy <i class="fa fa-anchor" style="font-size:20px;"></i></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="FishSpecies" asp-action="Index">Fish Species</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Contact">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - FishBuddy - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>